### ISSUE TITLE
能否增加微信赞赏码功能展示支持

### ISSUE THREAD

**Issue by VAllens** [greedying/tctip#12]
如题：能否增加微信赞赏码功能展示支持。
似乎在https://github.com/greedying/tctip/blob/master/src/utils/config.js的defaultList里增加多一个type和对应的图片就可以了

**Comment by greedying** [comment]
你好。支持自定义的哈~。 在list中 type 自定义，并且传入qrImg即可。可以具体看下文档的type部分

**Comment by VAllens** [comment]
哈哈，已解决。
谢谢。
新版打赏插件很强大，自由度很高，谢谢。

**Comment by greedying** [comment]
不客气
