### ISSUE TITLE
HTTPS加载的问题

### ISSUE THREAD

**Issue by yanshigou** [greedying/tctip#16]
tctip-1.0.3.min.js:1 Mixed Content: The page at 'https://www.dogebug.cn/' was loaded over HTTPS, but requested an insecure script 'http://stat.tctip.com/stat/index/version/1.0.3'. This request has been blocked; the content must be served over HTTPS.

**Comment by greedying** [comment]
你好，这个不影响，只是做一个统计。你可以把统一选项去掉

**Comment by greedying** [comment]
后续我也会把https加上的

**Comment by yanshigou** [comment]
> 你好，这个不影响，只是做一个统计。你可以把统一选项去掉

好的 非常感谢！

**Comment by greedying** [comment]
已经把统计代码加上https了⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by yanshigou** [comment]
> 已经把统计代码加上https了⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

改为1.0.4之后，打赏模块消失，在demo页面改为1.0.4，样式全部消失
