### ISSUE TITLE
top  是否可以自定义

### ISSUE THREAD

**Issue by jiangfeng0103** [greedying/tctip#5]
.myRewards {position:fixed; _position:absolute; right:0; **top:10%;** z-index:10000; padding-left:34px; width:0px; overflow:hidden; box-sizing: content-box;}

**Comment by greedying** [comment]
可以的，欢迎提交代码

**Comment by HaddyYang** [comment]
我Fork之后，修改添加该配置，可参考一下： https://github.com/haddyyang/tctip

**Comment by greedying** [comment]
将在v1.0支持，参考[issue#7](https://github.com/greedying/tctip/issues/7)

**Comment by greedying** [comment]
v1.0.0已经发布，支持top。欢迎使用
